// Auto-generated by build.ts — do not edit by hand.
// Contains the contents of the git-tracked storage/ directory so the
// standalone binary can extract its defaults on first run (see
// src/bootstrap.ts). Regenerated on every build.

export interface EmbeddedAsset {
  path: string;
  contents: string;
}

export const EMBEDDED_STORAGE: EmbeddedAsset[] = [
  {
    path: 'storage/config.json',
    contents: '{\n    \"meta\": {\n        \"version\": \"1.0.1\",\n        \"codename\": \"Pneuma\"\n    }\n}',
  },
  {
    path: 'storage/fileSpecifier.json',
    contents: '{\n    \"Web Development\": [\"html\", \"css\", \"js\", \"ts\", \"jsx\", \"vue\", \"scss\", \"php\"],\n    \"Documents\": [\"pdf\", \"docx\", \"txt\", \"xlsx\", \"pptx\", \"md\", \"odt\"],\n    \"Images\": [\"jpg\", \"png\", \"gif\", \"bmp\", \"svg\", \"tiff\", \"webp\"],\n    \"Videos\": [\"mp4\", \"mkv\", \"avi\", \"mov\", \"wmv\", \"flv\", \"webm\"],\n    \"Audio\": [\"mp3\", \"wav\", \"aac\", \"flac\", \"ogg\", \"m4a\"],\n    \"Archives\": [\"zip\", \"rar\", \"7z\", \"tar\", \"gz\", \"bz2\"],\n    \"Code\": [\"c\", \"cpp\", \"java\", \"py\", \"rb\", \"go\", \"rs\", \"cs\", \"sh\", \"bat\"],\n    \"System Files\": [\"dll\", \"exe\", \"sys\", \"so\", \"bin\", \"deb\", \"rpm\"],\n    \"Configuration Files\": [\"json\", \"yaml\", \"xml\", \"ini\", \"env\", \"conf\", \"properties\"],\n    \"Database Files\": [\"db\", \"sqlite\", \"sql\", \"csv\"]\n}',
  },
];
